name: 'Android CI'
description: 'Build, test, and release Android apps'

inputs:
  gradle_cmd:
    description: 'Gradle command to execute'
    required: true
    default: 'assembleDebug'
  tag:
    description: 'Release tag prefix'
    required: true
    default: 'Release'
  body_release:
    description: 'Release body'
    required: true
    default: 'Aplikasi ini otomatis dirilis.'
  file_output:
    description: 'Path to APK file'
    required: true
    default: './app/build/outputs/apk/debug/app-debug.apk'

runs:
  using: 'composite'
  steps:
    
    - name: Setting JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Memberikan Perizinan gradlew
      run: chmod +x gradlew
      shell: bash

    - name: Build APK
      run: bash ./gradlew ${{ inputs.gradle_cmd }} --stacktrace
      shell: bash

    - name: Melihat BERKAS REPOSITORY
      run: bash ls -la
      shell: bash

    - name: MELIHAT BERKAS BUILD
      run: bash ls -la ./app/build/outputs/apk/debug/
      shell: bash

    - name: Upload APK to Artifacts
      uses: actions/upload-artifact@v3.1.3
      with:
        name: ${{ github.repository }}
        path: ${{ inputs.file_output }}

    - name: Create Release and Upload Asset
      id: release-id
      uses: actions/create-release@v1
      env: # Pindahkan env ke dalam with
        GITHUB_TOKEN: ${{ github.token }}
      with:
        tag_name: "${{ inputs.tag }}-${{ github.run_number }}"
        release_name: ${{ github.repository }}
        body: ${{ inputs.body_release }}
        draft: false
        prerelease: false
      # Upload asset setelah release dibuat di step yang sama
      continue-on-error: true # Lanjutkan jika upload asset gagal

    - uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.release-id.outputs.upload_url }}
        asset_path: ${{ inputs.file_output }}
        asset_name: ${{ github.repository }}-${{ github.run_number }}.apk
        asset_content_type: application/vnd.android.package-archive
