name: Android CI

on:
  push:
    branches: [main]
inputs:
  body_release:
    default: "Aplikasi ini otomatis dirilis sesuai dengan Artefact"
    description: "Body Release"

  gradle_cmd:
    default: bash ./gradlew assembleDebug --stacktrace
    description: "Build Apk with ${{gradle_cmd.default}}"
 
env:
  TAG: Release
  PROJECT_NAME: ${{github.repository}}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  FILE_OUTPUT: ./app/build/outputs/apk/debug/app-debug.apk
 

jobs:
  using: composite
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Setting JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: memberikan Perizinan gradlew
      run: chmod +x gradlew
      
    - name: ${{inputs.gradle.gradle_cmd.description}}
      run: ${{inputs.gradle.gradle_cmd}}
    

    - name: Upload Ke dalam Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
          name: ${{env.PROJECT_NAME}}
          path: ${{env.FILE_OUTPUT}}

    - name: Pembuatan Membuat Tag Rilis
      id: release-id
      uses: actions/create-release@v1
      with:
          tag_name: "${{env.TAG}}-${{github.run_number}}"
          release_name: ${{env.PROJECT_NAME}}
          body: ${{inputs.body_release}}
          draft: false
          prerelease: false
             
    - name: Upload Release
      needs: release-id
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{steps.release-id.outputs.upload_url}}
        asset_path: ${{env.FILE_OUTPUT}}
        asset_name: ${{env.PROJECT_NAME}}-${{github.run_number}}.apk
        asset_content_type: application/vnd.android.package-archive

     
