name: TestRelease

on:
    push:
        branches: ["main"]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
    
    steps:
        - name: Check Out Folder
          uses: actions/checkout@v4
          
        - name: Membuat Teks
          run: "echo 'Hello World' > ./test.txt"
          
          