name: TestRelease

on:
    push:
        branches: ["main"]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            
        steps:
            - name: Check Out
              uses: actions/checkout@v4
            
            - name: Membuat File
              run: "echo 'Nete' > ./txt"
            
            - name: Cek nama Repository
              run: echo ${{github.event.repository.name}}
#            - name: Upload ke Artefak
#              uses: actions/upload-artifact@v3.1.3
#              with:
#                  name: ${{github.event.repository.name}}
                  
              
              